# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_data": "00_core.ipynb",
         "save_data": "00_core.ipynb",
         "split_fires": "00_core.ipynb",
         "to_polygon": "00_core.ipynb",
         "run_all": "00_core.ipynb",
         "fire_split_run": "01_cli.ipynb"}

modules = ["core.py",
           "cli.py"]

doc_url = "https://mnpinto.github.io/fire_split/"

git_url = "https://github.com/mnpinto/fire_split/tree/master/"

def custom_doc_links(name): return None
