# AUTOGENERATED! DO NOT EDIT! File to edit: 01_cli.ipynb (unless otherwise specified).

__all__ = ['fire_split_run']

# Cell
from fastscript import call_parse, Param
from pathlib import Path
from .core import *

# Cell
@call_parse
def fire_split_run(
    input_path:Param("Directory with tif files", str),
    output_path:Param("Directory to save outputs", str),
    interval_days:Param("Number of days to keep as same event", int)=8):

    path = Path(input_path)
    out = Path(output_path)
    run_all(path, out, interval_days=interval_days)